const dummyData=[{id: 1, source: 'abc-news-au',conservative:0,liberal:10},
{id: 2, source: 'al-jazeera-english',conservative:4,liberal:13},
{id: 3, source: 'associated-press',conservative:10,liberal:3},
{id: 4, source: 'bbc-news',conservative:10,liberal:30},
{id: 5, source: 'bloomberg',conservative:10,liberal:3},
{id: 6, source: 'breitbart-news',conservative:100,liberal:33},
{id: 7, source: 'business-insider',conservative:21,liberal:20},
{id: 8, source: 'buzzfeed',conservative:90,liberal:213},
{id: 9, source: 'cnbc',conservative:10,liberal:300},
{id: 10, source: 'cnn',conservative:10,liberal:200},
{id: 11, source: 'daily-mail',conservative:101,liberal:3},
{id: 12, source: 'entertainment-weekly',conservative:1,liberal:33},
{id: 13, source: 'financial-times',conservative:10,liberal:3},
{id: 14, source: 'fortune',conservative:100,liberal:3},
{id: 15, source: 'google-news',conservative:15,liberal:23},
{id: 16, source: 'hacker-news',conservative:10,liberal:30},
{id: 17, source: 'independent',conservative:10,liberal:33},
{id: 18, source: 'metro',conservative:103,liberal:3},
{id: 19, source: 'mirror',conservative:102,liberal:3},
{id: 20, source: 'mtv-news',conservative:1,liberal:13},
{id: 21, source: 'mtv-news-uk',conservative:23,liberal:39},
{id: 22, source: 'national-geographic',conservative:10,liberal:5},
{id: 23, source: 'newsweek',conservative:1,liberal:13},
{id: 24, source: 'new-york-magazine',conservative:10,liberal:93},
{id: 25, source: 'reddit-r-all',conservative:13,liberal:63},
{id: 26, source: 'the-economist',conservative:99,liberal:21},
{id: 27, source: 'the-guardian-uk',conservative:102,liberal:55},
{id: 28, source: 'the-huffington-post',conservative:1,liberal:93},
{id: 29, source: 'the-new-york-times',conservative:12,liberal:99},
{id: 30, source: 'the-telegraph',conservative:102,liberal:63},
{id: 31, source: 'the-times-of-india',conservative:101,liberal:34},
{id: 32, source: 'the-wall-street-journal',conservative:10,liberal:77},
{id: 33, source: 'the-washington-post',conservative:1,liberal:88},
{id: 34, source: 'time',conservative:43,liberal:31},
{id: 35, source: 'usa-today',conservative:10,liberal:23}
]
export default dummyData
